/*
Lucas Systems Inc
11279 Perry Highway
Wexford
PA 15090
United States
 
 
The information in this file contains trade secrets and confidential
information which is the property of Lucas Systems Inc.
 
All trademarks, trade names, copyrights and other intellectual property
rights created, developed, embodied in or arising in connection with
this software shall remain the sole property of Lucas Systems Inc.
 
Copyright (c) Lucas Systems, 2014
ALL RIGHTS RESERVED
 
*/

"use strict";

describe('Unit testing MoveDataGrid directive', function() {
    var $compile;
    var $rootScope;
    var localElement;
    var $httpBackend;
    var $interval;
    var mockWidgetController;
    var timeout;
    var localWidgetService;

    beforeEach(module("amdApp"));

    beforeEach(inject(function(_$compile_, _$rootScope_, _$interval_, _$httpBackend_, $timeout, WidgetService) {
        $compile = _$compile_;
        $rootScope = _$rootScope_;
        $interval = _$interval_;
        timeout = $timeout;
        localWidgetService = WidgetService;

        // Set up the mock http service responses
        $httpBackend = _$httpBackend_;
        // Handle all the POST requests
        $httpBackend.when('GET').respond({
            data: {}
        });

        $rootScope.widgetgriddetails = {
            "availableItems": [{
                "lastName": "Lucas System",
                "skill": null,
                "userName": "system",
                "firstName": "Lucas System"
            }, {
                "lastName": "User",
                "skill": null,
                "userName": "admin123",
                "firstName": "Admin"
            }, {
                "lastName": "User1",
                "skill": null,
                "userName": "jill123",
                "firstName": "Jill"
            }, {
                "lastName": "User2",
                "skill": null,
                "userName": "jack123",
                "firstName": "Jack"
            }, {
                "lastName": "User3",
                "skill": null,
                "userName": "joe123",
                "firstName": "Joe"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username6",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username7",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username8",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username9",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username10",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username11",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username12",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username13",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username14",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username15",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username16",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username17",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username18",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username19",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username20",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username21",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username22",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username23",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username24",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username25",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username26",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username27",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username28",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username29",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username30",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username31",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username32",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username33",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username34",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username35",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username36",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username37",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username38",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username39",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username40",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username41",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username42",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username43",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username44",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username45",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username46",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username47",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username48",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username49",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username50",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username51",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username52",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username53",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username54",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username55",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username56",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username57",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username58",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username59",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username60",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username61",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username62",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username63",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username64",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username65",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username66",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username67",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username68",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username69",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username70",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username71",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username72",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username73",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username74",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username75",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username76",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username77",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username78",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username79",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username80",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username81",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username82",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username83",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username84",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username85",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username86",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username87",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username88",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username89",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username90",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username91",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username92",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username93",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username94",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username95",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username96",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username97",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username98",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username99",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username100",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username101",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username102",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username103",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username104",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username105",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username106",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username107",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username108",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username109",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username110",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username111",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username112",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username113",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username114",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username115",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username116",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username117",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username118",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username119",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username120",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username121",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username122",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username123",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username124",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username125",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username126",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username127",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username128",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username129",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username130",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username131",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username132",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username133",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username134",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username135",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username136",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username137",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username138",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username139",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username140",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username141",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username142",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username143",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username144",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username145",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username146",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username147",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username148",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username149",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username150",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username151",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username152",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username153",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username154",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username155",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username156",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username157",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username158",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username159",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username160",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username161",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username162",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username163",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username164",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username165",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username166",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username167",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username168",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username169",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username170",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username171",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username172",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username173",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username174",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username175",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username176",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username177",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username178",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username179",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username180",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username181",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username182",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username183",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username184",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username185",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username186",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username187",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username188",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username189",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username190",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username191",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username192",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username193",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username194",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username195",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username196",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username197",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username198",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username199",
                "firstName": "dummy-firstName"
            }, {
                "lastName": "dummy-LastName",
                "skill": null,
                "userName": "dummy-username200",
                "firstName": "dummy-firstName"
            }],
            "existingItems": [{
                "lastName": "User2",
                "skill": null,
                "userName": "jack123",
                "firstName": "Jack"
            }, {
                "lastName": "User1",
                "skill": null,
                "userName": "jill123",
                "firstName": "Jill"
            }, {
                "lastName": "Lucas System",
                "skill": null,
                "userName": "system",
                "firstName": "Lucas System"
            }],
            "selectedAvailableItems": [],
            "selectedExistingItems": []
        };

        localElement = $compile("<move-data-grid widgetgriddetails='widgetgriddetails'></move-data-grid>")($rootScope);


        $httpBackend.flush();
        $rootScope.$digest();
    }));

    // Verifies that all of the requests defined via the expect api were made.
    // If any of the requests were not made, verifyNoOutstandingExpectation throws an exception.
    afterEach(function() {
        $httpBackend.verifyNoOutstandingExpectation();
        $httpBackend.verifyNoOutstandingRequest();
    });

    it('Should create MoveDataGrid directive', function() {
        expect(localElement.length).toBeGreaterThan(0);
    });


    it('should show the currect number of availableItems', function() {
        var isolatedScope = localElement.isolateScope();
        expect(isolatedScope.gridOptions.data.length).toEqual($rootScope.widgetgriddetails.availableItems.length - $rootScope.widgetgriddetails.existingItems.length);
    });

    it('should show the currect number of existingItems', function() {
        var isolatedScope = localElement.isolateScope();
        expect(isolatedScope.existingGridOptions.data.length).toEqual($rootScope.widgetgriddetails.existingItems.length);
    });

    it('should check grid columnDefs', function() {
        var colDefs = [{
            "enableColumnMoving": true,
            "enableColumnResizing": true,
            "name": "lastName",
            "type": "string",
            "width": 150
        }, {
            "enableColumnMoving": true,
            "enableColumnResizing": true,
            "name": "skill",
            "type": "string",
            "width": 150
        }, {
            "enableColumnMoving": true,
            "enableColumnResizing": true,
            "name": "userName",
            "type": "string",
            "width": 150
        }, {
            "enableColumnMoving": true,
            "enableColumnResizing": true,
            "name": "firstName",
            "type": "string",
            "width": 150
        }];
        var isolatedScope = localElement.isolateScope();
        expect(isolatedScope.gridOptions.columnDefs).toEqual(colDefs);
        expect(isolatedScope.existingGridOptions.columnDefs).toEqual(colDefs);
    });

    it('should handle moveAllToExistingData', function() {
        var isolatedScope = localElement.isolateScope();
        $rootScope.widgetgriddetails.existingItems = [];
        isolatedScope.moveAllToExistingData();
        expect($rootScope.widgetgriddetails.selectedAvailableItems).toEqual([]);
        expect(isolatedScope.existingGridOptions.data.length).toEqual($rootScope.widgetgriddetails.availableItems.length);
        expect(isolatedScope.gridOptions.data).toEqual({});
    });

    it('should handle moveAllToAvailableData', function() {
        var isolatedScope = localElement.isolateScope();
        isolatedScope.moveAllToAvailableData();
        expect($rootScope.widgetgriddetails.selectedAvailableItems).toEqual([]);
        expect(isolatedScope.gridOptions.data.length).toEqual($rootScope.widgetgriddetails.availableItems.length);
        expect(isolatedScope.existingGridOptions.data).toEqual({});
    });

});