package com.lucas.alps.viewtype;

public interface BaseView {
	
	String ZERO_LENGTH_STRING = "";

	String DATE_FORMAT_USER_SEARCH_BY_COLUMNS = "M/dd/yyyy";

	int TOTAL_NO_OF_GRID_COLUMNS = 28;
	int TOTAL_NO_OF_PRODUCT_GRID_COLUMNS = 14;
	int TOTAL_NO_OF_MESSAGE_GRID_COLUMNS = 5;
	int TOTAL_NO_OF_SEGMENT_GRID_COLUMNS = 3;
	int TOTAL_NO_OF_MAPPING_GRID_COLUMNS = 4;

	int TOTAL_NO_OF_EVENT_GRID_COLUMNS = 6;

}
